name: Tests

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

env:
    PY_COLORS: "1"

jobs:
    build:
        name: ${{ matrix.os }} (py ${{ matrix.version }}${{ matrix.special }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
                special: [""]
                include:
                    -   os: ubuntu-latest
                        special: "; pre-release"
                        version: "3.11"
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: ${{ matrix.version }}

            -   name: Install dependencies
                run: |
                    case "${{ matrix.special }}" in
                        "; pre-release")
                            pip install -e .[test,doc] --pre --upgrade --force-reinstall
                            pip install git+https://github.com/SCM-NV/PLAMS@master --upgrade
                            ;;
                        *)
                            pip install -e .[test,doc] ;;
                    esac

            -   name: Info Python
                run: |
                    which python
                    python --version

            -   name: Info installed packages
                run: pip list

            -   name: Run tests
                run: pytest

            -   name: Run codecov
                uses: codecov/codecov-action@v3
                with:
                    file: ./coverage.xml
                    name: codecov-umbrella
